const module = {
  head1: {
    fontSize: 30,
    color: "black",
    textAlign: "center",
    // backgoundColor: "#f50057",
  },
  head2: {
    fontSize: 20,
    color: "#gray",
    textAlign: "center",
    // backgoundColor: "#f50057",
  },
  formgroup: {
    // flex: 1,
  },
  label: {
    fontSize: 16,
    color: "#000",
    marginLeft: 20,
    marginBottom: 5,
  },
  input: {
    fontSize: 16,
    color: "#000",
    borderRadius: 15,
    padding: 10,
    // borderWidth: 1,
    margin: 15,
    backgroundColor: "#eeb000",
  },
  input1: {
    fontSize: 16,
    color: "#000",
    borderRadius: 15,
    padding: 10,
    // borderWidth: 1,
    margin: 15,
    height: 130,
    backgroundColor: "#eeb000",
    textAlignVertical: "top",
    // maxWidth: 200,
  },
  link: {
    color: "black",
    fontSize: 12,
  },
  fp: {
    display: "flex",
    // alignItems: "flex-end",
    marginHorizontal: 10,
    marginVertical: 10,
  },
  buttonCont: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    width: "80%",
    alignItems: "center",
  },
  button1: {
    width: "90%",
    marginHorizontal: 10,
    marginVertical: 10,
    backgroundColor: "green",
    padding: 5,
    paddingHorizontal: 30,
    borderRadius: 15,
    fontSize: 25,
    textAlign: "center",
    zIndex: 1,
  },
};
export default module;
